apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotifyme.fullname" . }}
  labels:
    {{- include "gotifyme.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gotifyme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gotifyme.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gotifyme.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: GOTIFY_ENDPOINT
              value: {{ .Values.gotify.endpoint | quote }}
            - name: GOTIFY_USERNAME
              value: {{ .Values.gotify.username | quote }}
            - name: GOTIFY_PASSWORD
              value: {{ .Values.gotify.password | quote }}
            - name: NOTIFYPASS
              value: {{ .Values.gotify.notifyPass | quote }}
            - name: ENABLE_OTEL
              value: {{ .Values.otel.enabled | quote }}
            - name: GOOGLE_CLOUD_PROJECT
              value: {{ .Values.otel.googleCloudProject | quote }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/mnt/sa/{{ .Values.otel.googleApplicationCredentialsFile }}"
          {{- if .Values.otel.enabled }}
          volumeMounts:
            - name: gcp-sa-json
              mountPath: /mnt/sa
              readOnly: true
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.otel.enabled }}
      volumes:
        - name: gcp-sa-json
          secret:
            secretName: {{ .Values.otel.googleApplicationCredentialsSecret }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
